### PR TITLE
Add option to allow sorting jpg files into both year and month directories

### PR DESCRIPTION
**Pull request by woutgg**
First of all thanks for this great little program!

The PR also adds argparse because otherwise adding another commandline argument would become quite messy.
I did some cleanup of indentation as well; if this is confusing while reviewing changes, I could create a new PR with as little non-code changes as possible.

### CODE REVIEW

**Comment by tfrdidi** [comment]
Thanks for you adjustments =) looking forward for future adjustments ;-)

**Comment by woutgg** [comment]
You're welcome. :) This program is a very useful addition to Photorec.
I noticed you've been busy extending the program further with nice additions too! If I may make one small note: in the updated readme, you included a graph showing the sorted months as '1' and '2'; which should really be '01' and '02' as that is often important for correct ordering by most programs.

As for future additions, I have some in mind (although my current real-world use case is finished :)). I would particularly like to ask @dispiste if it's okay to combine [the commit which sets file creation/modification times](https://github.com/dispiste/sort-PhotorecRecoveredFiles/commit/22af2664ff2a27fb9fcd5540aef0a3aca1896009).

**Comment by dispiste** [comment]
@woutgg Please, go on. I don't remember which changes I did (fortunately I could successfully recover my data), but I am happy if they can be useful for anyone else

**Comment by tfrdidi** [comment]
Looking Forward the Next PR;)

**Pull request merged**
